version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/swasthify
    depends_on:
      - mongo
      - flask

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flask:
    build: ./flask
    ports:
      - "8080:8080"
